[2022-10-10 16:23:33,818] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available __airflow_temporary_run_2022-10-10T16:23:15.380166+00:00__ [queued]>
[2022-10-10 16:23:34,299] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available __airflow_temporary_run_2022-10-10T16:23:15.380166+00:00__ [queued]>
[2022-10-10 16:23:34,305] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-10 16:23:34,309] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-10 16:23:34,314] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-10 16:23:35,369] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-01-01 00:00:00+00:00
[2022-10-10 16:23:36,240] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', '__***_temporary_run_2022-10-10T16:23:15.380166+00:00__', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmphcfzp6rj', '--error-file', '/tmp/tmpt4s8k5ac']
[2022-10-10 16:23:36,251] {standard_task_runner.py:80} INFO - Job 19: Subtask is_api_available
[2022-10-10 16:23:36,221] {standard_task_runner.py:52} INFO - Started process 6445 to run task
[2022-10-10 16:23:37,640] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available __airflow_temporary_run_2022-10-10T16:23:15.380166+00:00__ [running]> on host 09023156d4e0
[2022-10-10 16:23:39,511] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=__***_temporary_run_2022-10-10T16:23:15.380166+00:00__
[2022-10-10 16:23:39,543] {http.py:97} INFO - Poking: api/
[2022-10-10 16:23:39,739] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-10-10 16:23:39,844] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-10-10 16:23:41,473] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-10 16:23:41,921] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220101T000000, start_date=20221010T162333, end_date=20221010T162341
[2022-10-10 16:23:42,457] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
